### ISSUE TITLE
Features may contain non-ascii characters.

### ISSUE THREAD

**Issue by typesupply** [typesupply/ufo2fdk#11]
See this PR for details:

https://github.com/typesupply/ufo2fdk/pull/7

Address this by joining the strings with u"\n\n" instead of "\n\n".

cc @adrientetar

**Comment by adrientetar** [comment]
@typesupply: Okay so I had a look and the deeper cause of the problem is that `join()` is passed a mix of str and unicode &ndash; indeed, `writeFeatures_name()` that writes the name table promotes its string to a unicode one when using the `winStr()` and `macStr()` functions of FeatureTableWriter:

~~~
def winStr(text):
    """
    Convert string to FDK encoding for Windows.
    """
    return "".join([winCharEncode(c) for c in unicode(text)])

def macStr(text):
    """
    Convert string to FDK encoding for Mac.
    """
    return "".join([macCharEncode(c) for c in unicode(text)])
~~~

Casting these back to str seems to fix the issue. Should I send of PR for that? Ignoring UnicodeDecodeError on the join would be another option.
