### ISSUE TITLE
haveFDK

### ISSUE THREAD

**Issue by typemytype** [typesupply/ufo2fdk#19]
FDK is changing tools and it possible that `checkoutlines` is not available anymore in favour of `checkOutlinesUFO` when installing FDK from source.

@adobe-type-tools could you confirm this?

**Comment by miguelsousa** [comment]
That's correct, `checkoutlines` is not available from the open source repository.

**Comment by typemytype** [comment]
thanks Miguel

I guess checking on `makeotf`and `autohint` should be sufficient. There will be a big transition period until most people changed to a more recent FDK version, so checking on `checkOutlinesUFO` is not 

https://github.com/typesupply/ufo2fdk/blob/master/Lib/ufo2fdk/fdkBridge.py#L45

I well send a pull request, that checks for both `checkoutlines` and `checkOutlinesUFO`

**Comment by miguelsousa** [comment]
@typemytype Because building the FDK from source is not something trivial, I expect that most people will download the package that has the compiled tools, which includes `checkoutlines`. We don't have any plans to remove the compiled `checkoutlines` from that download.
The motivations for developing `checkoutlinesUFO` were 1) `checkoutlines` has code that can't be open sourced, and 2) `checkoutlines` relies on an old library that is complicated to maintain and to patch.

**Comment by typemytype** [comment]
I understand, this is just a small patch as I received an email that the Generate menu item in RoboFont was grayed out, due to an install of FDK from source. That menu item is bind to `haveFDK()`.

**Comment by typesupply** [comment]
Could you apply this to the ufo3 branch as well?

**Comment by typemytype** [comment]
I thought I did: https://github.com/typesupply/ufo2fdk/pull/21

**Comment by mathieureguer** [comment]
I think `ufo2fdk` is still using `checkOutlines` when `checkOutlinesUFO` has been around for a long time now. 
Installing the afdko with pip is now easy and straightforward, but it does not include the old `checkOutlines`, breaking `ufo2fdk.compileOTF`. Should we move to `checkOutlinesUFO` in `fdkBridge`?

**Comment by benkiel** [comment]
Yes we should

**Comment by mathieureguer** [comment]
I can try to make a PR. I'll keep you posted.
